### ISSUE TITLE
Connection Lost immediately after joining server on Raspberry pi 1 Model B.

### ISSUE THREAD

**Issue by Dependability** [MCCTeam/Minecraft-Console-Client#1303] opened 2020-10-31 18:59 UTC
I was trying my best to find a solution on my own, I looked through all issues, googled it many times, but I could not find anything. It says that I joined the server, but immediately after, I am disconnected. Console Client works fine on my laptop however.

This is the version of mono, I am using.
![monoversion](https://user-images.githubusercontent.com/58313642/97787533-e4018200-1b80-11eb-9714-9b90ba1c6f16.PNG)

This is what it looks like.
![Problem](https://user-images.githubusercontent.com/58313642/97787534-e49a1880-1b80-11eb-8352-78b3cd8de17c.PNG)

I tried building it from scratch, and the same problem happens. I have also used the screen command, and the same thing happens. I am thinking maybe it is something like firewall disconnecting it, but if that was the case, then I think it would show some sort of error.  I am open to any suggestion, and will do everything. Thank you.

**Comment by ORelio** [comment] 2020-10-31 20:10
I'm not sure of the reason. Please try setting `debugmessages=true` in configuration, this might produce additional output.

**Comment by Dependability** [comment] 2020-10-31 20:28
Thank you for the speedy reply. 
Below is everything I input, and what was output in the console.

pi@pi:~/MinecraftClient $ mono MinecraftClient.exe
Console Client for MC 1.4.6 to 1.16.3 - v1.16.3 - By ORelio & Contributors
AppVeyor build 418, built on Fri 10/30/2020 from commit d3ea597
[MCC] [Settings] Loading Settings from /home/pi/MinecraftClient/MinecraftClient.ini
Resolving mccentral.org...
Found server sponsor1234.mccentral.org:25565 for domain mccentral.org
[MCC] [Translations] No translation file found for en. (Looked '/home/pi/MinecraftClient//lang/mcc/en.ini'
[MCC] [Translations] No translation file found for system language (en). (Looked '/home/pi/MinecraftClient//lang/mcc/en.ini'
Color test: Your terminal should display [0123456789ABCDEF]: [0123456789ABCDEF]
[SessionCache] Initializing FileSystemWatcher for file: /home/pi/MinecraftClient/SessionCache.ini
Loading session cache from disk: SessionCache.ini
Loaded session: danielpeterson099@gmail.com:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzOGUwYWNiMThiOGUzZDM1Mjc5YzhjNDk1ZjEyNjQyMiIsInlnZ3QiOiIxZGM1MjQ2NWVjMjM0YmFjODZhMGRjNzUxNzAxYzU2MCIsInNwciI6IjhjZjZjYmIxMTk2ZTQ3ZWQ4NDY5YzE4YmNiOTQyOTk0IiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE2MDQzNDU0MjAsImlhdCI6MTYwNDE3MjYyMH0.PY148FhdoEJQJEdkHnGVPBEm3Y4xZlosf78D5QmoGas
Session data has been successfully loaded from disk.
Performing request to authserver.mojang.com
> POST /validate HTTP/1.1
> Host: authserver.mojang.com
> User-Agent: MCC/1.16.3
> Content-Type: application/json
> Content-Length: 389
> Connection: close
> 
> {"accessToken": "eyJhbGciOiJIUzI1NiJ9\u002eeyJzdWIiOiIzOGUwYWNiMThiOGUzZDM1Mjc5YzhjNDk1ZjEyNjQyMiIsInlnZ3QiOiIxZGM1MjQ2NWVjMjM0YmFjODZhMGRjNzUxNzAxYzU2MCIsInNwciI6IjhjZjZjYmIxMTk2ZTQ3ZWQ4NDY5YzE4YmNiOTQyOTk0IiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE2MDQzNDU0MjAsImlhdCI6MTYwNDE3MjYyMH0\u002ePY148FhdoEJQJEdkHnGVPBEm3Y4xZlosf78D5QmoGas", "clientToken": "4c4e356e0b7d4227a8e0593fde6cfda7" }

< HTTP/1.1 204 No Content
< Connection: close
< Accept-Ranges: bytes
< Date: Sat, 31 Oct 2020 20:22:29 GMT
< Server: Restlet-Framework/2.4.1
< X-Cache: Miss from cloudfront
< Via: 1.1 a77dd74bb9c72f0eb05ce504c2023f4b.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: DFW3-C1
< X-Amz-Cf-Id: xKUqMsXxBjy9H63J9uo5YlHVdB-kJf3pSATl1dcCnzDhYe6fpjfCdg==
< 
< 
Cached session is still valid for SaucyTortoise.
Success. (session ID: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzOGUwYWNiMThiOGUzZDM1Mjc5YzhjNDk1ZjEyNjQyMiIsInlnZ3QiOiIxZGM1MjQ2NWVjMjM0YmFjODZhMGRjNzUxNzAxYzU2MCIsInNwciI6IjhjZjZjYmIxMTk2ZTQ3ZWQ4NDY5YzE4YmNiOTQyOTk0IiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE2MDQzNDU0MjAsImlhdCI6MTYwNDE3MjYyMH0.PY148FhdoEJQJEdkHnGVPBEm3Y4xZlosf78D5QmoGas)
Retrieving Server Info...
{"description":{"text":"   §c§lI§d§l§m--§c§l§m-§6§l§m-§e§l§m-§b§l§m--§8§l[§r §b§lMinecraft Central§r §8§l]§b§l§m--§e§l§m-§6§l§m-§c§l§m-§d§l§m--§c§lI             §c§l»§6§l»§e§l» §a§lFactions Server Reset §e§l«§6§l«§c§l«"},"favicon":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAJnKAACZygHjkaQiAAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAABYhSURBVHja1Jp5lGVVdf8/+9x736tXU3dVV/U80tDMdBtBaRAV7MVCWUuMICEJQSVx8fNnCGgScVgmCsbEhT8BNZr8IqjIpEkzKaONDDbSNE1DD0zd1dVT9VjVNdd79YZ7vvnj3ldd1fRQGDB41rqrVr337jlnf88evnvvY4x/NGB2FmZn4NxkpBjv1yD9CtjEH+iwcfxmIWH4OeCsWmneLDMmAxVgk8ReGMDs13j/CN7/FBh8/Sp2IUHwXszmIrUAO/D+aby/G9j+NobHFhKGm+cGgb5kpl+B9oCGQUOg1aAvO6dzgkANYSjC8GngXCBMZ1hMEDyQDUO9Kwh0Kegq0AedU1MYiiDYhXP/CMx9Owp/DlG0b6pzehSkAx8zyUwbamq0vK5O38lmNT8IRBTlgQ8DZ1smk5/lnH6QAjb6/d+CLjZTcxSJMNyC2SVA9DaR3T5MJlM4zUyr0g17ULxokeLLLpM/5hj59PPOMNSy+nr9prFRd+ZymhcEwrlXCIJX5waBVleFPv986eGH5a+9VqqrUxn0Ym2tbq+t1YWZjMIo8jj3A6AVcEfY4ujvgzdb/lbCcNuJzqmtKvzMmfJ33SXf3y8vyb/6qvzixWNA+HVdnZ5paNBnwlAum5Vls7q8KvwVV8gXCpIkL0lXXqlB0MpcTr9uaNDy+npdHkWyKBJm1wFN6V5awD6GBd8yC26F4D4IngS3Buy+5HHrwD2KBbeY2V//z83Jua/WhKFurQo/dar8I49o9PCS/A03yKeaIVBbJqMnGhr0zWxWuVxOYS6n74F0/PFSf//+d+NY8aWXSqCimV7KZvVYQ4MeqavTyYkf6QC7FtydEO2sq42UzQSKQlNzg2lWq+nYmWjhUeidx6B3HI3mTUW5rAmcIOgGu9PMLgSmHknc8ID/57lM5rMLikU+DNDYCD/5CZx77uvfXLeuai8ATIpjdgI1ZgwXCjQCiwHOOQcaGpLfeg9XX43dcQcyIwMsKJXoDkMyznFhEPByXJ5xzBy+MnOSWHxChUXzRWHYqHhomSBqs0YUGplwZGlKZdjbK5avFw8/R9PWvXbJ0LC7BGyPWXyzpJuAvUcCoDEIgru81PgOiQkAl16KHUz4m2+Gn/50zEe1EhnvqXMOAyYDswGm7j8EPf88fPe7I8AJCCWml8tsymY5LQiZVixy1inw71cbFgFFY7gE5QoMl404hoEC9A1BsZw6gQBmTzY+fi5ceBbs7YN17TE/ftSmtO+yL5nZH0v+GuABwB8KgI966V0Ui5wNkMmgD35wDFFQdzf84Adw/fVQLu8/AiBKAZgUBDSbMVdiIkB7OwLYswd9+9vJfKPew4zmOKZdYkJgLCJgVVtMcRhq0p/UZJMn1SOmCool6M9D7yB0D0ChlAASOJjZAvOnGaefAN+/33Pv03a8mbsL9E+Svg/0V4EIR3n+D0iiHjipenILF449+RtvhOuuG6P6AAJMIus9DWHITOeYFceEZrB0Kerrw155BXvllbHCp6Pee3LeoyDgWBeyuitmb5+YXWsoThc4YGQz0JqF1omiP29s2yP68kbswSvRmKZ6+NplxqRGcfNDqnVB8HXFcR64HegC5EZcn3PHIXEMsABgwYKx6lsooGXLXif8gbTSARNT9Qagvx+7+244hPDVOBZJVIA5oaM4CHt7D89TJfAxSEZjLZw4z5jVKnxKNCABoVCCv77AOO808DEWBMHVwB8BtaPjadYnFJULSFRNra0QjeIlmzdjGzce1qMGwKBEu/eJD6mCVX2OENgF1DujXIQd+47MBqpTeiUvz55izGwZ+xvvIY4TECZPjPGeOWb2x8A0wFWXaBQ0ApxRffO556C9PUF7aAj9679CV9ehBTGj0Xvqy2VaJBaNMo/DDaUHnZEQEMnjPezrP5huHXoSVUGYDPW5FJR0lCowZzJc8v50NufeAxwL5Ko+YBrQXANMr0Lb1oYuvRTOOw+tWIE99NARBZlaqdAC3C/RYjZ+7iERShgw5D2VA7XfDBFiKh7ULqpLScmRRuEoZNMxXIYlfwR3PiE6+6hPRa0NUwc4QwntYqrZiBHZM8/AM8/sn+cIQin1qjPS3+mNEDAzHLBBomiJAxtj8MTjTF5TZnaQz2qyRjb0IMuSBJmwqldzSSGpclDOPx998pMQhuMSfjQI+h2Erx5Yl5L43zph9CTCiI88TQBDhYQnuAO2m4mgbYfY2+sAdqZpezlM0FGOahYiwQUXwD33YGZo4kTshhve8gSsyk6GgSBKNUDjxg8MhvJiW2dClqrezQBziR+483GjVCEGrU/rEIMujYGzqhoAoHPPxcySly+/HGpr98eWt2JIRD6BYNiL2iw01h4ZAENYVlADA0OwcYfRNwRhkBqLoOITPf/54+I36xxmagPWAJuB4aoGzACYUp05n9+/ysaNUCyOLSFJY4lQFZw34vgOxMA5isBmeZrqoLHORtTiYNNbCGSn8uSqAg893cfzG43+AlTiNPT5xHAqlWSvW/cYZuqS9ACwKjWDlAmateL9CPXkllvQvHkwNAT/8i9JIE01YsA52qOImeUy/d7TIlHf2Jj4iu7ukV0eFKjDABBJ5L1nJ2JWLWSjUS9YNdQp0cxQbO5s5lM31fH4s33yse0DtoK2gfWP8seW0BN5YChV/VXAy0BhBAAzq1eVGpklrO2iiw4aZwbM2J3JsEvic8Uin3eOT/zHf6BsNnmnUsHMKAO7oggXx2yTkszwEOzRm1Eyo9N7uvEcG0FgBxQuLWF9VdbU3RezfuM+fFyuwptJOJy2g60GvQTamIaPKCUSMZAHSqOTIQeEmLFgtK4dSq3NyEi0m7EZiKZOhY98BLZtS7SgUgGgJwhor6lhebHIdaUSD5ix5BBaMOQcPWFIb6WCgNosuODQzE8l453zB9hwazMPPzvBlq3sbenoomVXT3jyzq7KkoG8KBStF/ydwPWpvR+yHpDxUBdKNB9stUOc2mBKfRfMmAGZDLS1wfDwiKaUzQiAbSncL0gsOdicEgPOUTKj2TnAmDRBuCgpPY+2otHcRrFojLq4+ANw8RKDkrFpR8zGDsgPizWbmHjLo9GnOzrtY0b5O5K+AwwcLB0O8D4TJ0YyrnBlQDHVpa1tbZz2jW9gTz6ZbNCSiN0bBOSAfKpJiw4zZ3nEaBPxGmrHURUE5C21ZDAn5rRWyBeS+sExM+D9i+Abd9KybHVwLVQG0yywc7QihkAdzjXUxDHZcQBQTJ3hoITMuKqnh/jLX+ZPRmlNlxkvOUdvpcKzccwkYOFhNCocATWhUHMnp64rPXKNo4khD2FkTKyDrUNJNGhpKHPJ++CZlyOGCu6j4FentYDhsWubcTJw2jjCWJWQ7pUgCAo7vR+8DFpz3vNhYJ3E30isK5XoAyoSJwF1R5g3ADpSLtA6Yay5aTwIpDYyOgkaLhuzJ4vJE8XmgpsGfhawdjQADhjE+/6B0a7xMKPiHGVgvQTe9+H9LSXndnzbjG1mfM6MJ8Iw3uf9k5U4/hnO+d4jzJ0SOTriBICjpo611HFk0xhJtO4dGuUnBLkMOCdAWaAeyByYhpfMbGhLmogcboGScwwGAe1xzNo4BqkPWIv363YAq8OQ9jAE7zfh/b1IPzFpaCfw1AHC2qgDrQVyEu2VCpkcHDPjdyBUDgbzkB/eT4NrMvDUeujoBHMjyYQdaH5lvF9fgOPvB049zBp9zlE049FSiQHvBbwIiCA4ZUGlQpNzlL0HqTPl2s8adHg4foXEBWb0A7sF2xFbgH1AZ7lCsRyzHc/8ycmGp7VAJpd423GRcMGe3oQFOpcQqY4uuGkpFEuGWbwF6B2t/qNrgvfj3Mce856v7SderwtXPUHAAPByEpt2I70I9GE2pVWiLY7pT3S1mD7dkm7Hua//1nu+IPGf1fp0HUxohQnN0Dop4R3T8tDZCed+UZwyB/7fp+GMUw0rg8qHUX+XFEl7hxJTiUIYLsE//Fjs7XOEIeVKRS+nhzL0OgAkLcNs4FVo6ABmHayFbJaYgER3IuTGNMwvd3H8k3ui6PL7gME43ou0Angtya5N+CB+Ch90LICLL4Z3nAzzZsPM6ZCtMXp6aiiXHOAZGBCvvCZuvb3Mh74Uc9kScdVFxvw5oOLBTVOCrXuS02+sTeqA190unt9oBIHFcRyvBJ5P6DLlg2nAbsyeHTBb0iExazSfr8ZqM7wZm72nB2KkTUAHMOjj+Ip+71dhNg3v1wG7ky6xfUZyx5+5uMIFF8Cf/ylMnz0F+EAK85NQWUFNpkh3T0R/f0h9vfHeM+HdpwX8bGmZf/thicdeFHd/1Tj2hFSvKiTV4tT2d3clfYL+IfjNOnhwpXhijeGcFeM4/gXwC+BpYM/hkurP5JzTQ6M6vzJTJf3bGwR6rLZW52YyIgh2A18BjjtIcArNbCmYggBd83eoMICkoyRdIx+3JS0yL/n4VfnhWVIJqYg6d0Z66YV6rVtdr5fX1Ktjc4MevD8rDJ16NLrvn9DK76Gee0x6wqRlpv770Av/Zvrl100Lj6rWYpxcEOSBpcCfAzOOHESdu6wminRvCkDeTJ8FnWqm60B9YaibMhnlokg49yzw8bSKNqax6lzwFDid9k70y3uR5CR9RT7eowOHjzfLD8+SH0Z+2KQSGuwO9OraOq1bXa/1L9TrtfX1uuu2nKZNN0GoulxGx8823fy3SE+Zdv7MtPQf0bGznCCSc65gZsuB69K7ClPHxyvNLs8FgR4CxUGgr5uJIBBhmK9xTkvDUN+rqVEYhsLsEeD8agKZjuOCIFwDTu85E3V3IqlRin8o7/3rm6vxCvni2SPCVx+VTf1doda/UD/ybN/UoNt+XKMoEwjCEoRduWyg27+A+u8zXfkRBBmBPQn8fdqWnHvA/o7QZzc7KpJoAraFIfc6B2Y9xPGKYefYINEwtpdWGk1XnHM3xbE/paHBc8P10NQCqnwW2V9iIyymgOKlqHwJKp8Hevx1mqkYGhorNDeV8T75rq9fvOfMiP/zV4ZZHEL8QqHour7/C6NnADLhCPVpA5YDzwFb0nRlnAA4t2hK2tDcAexOUuLdwN7QjEaJZjPqE7Ca06pqNWk93cwtAc8X/h5OXQwqfwiCa0aVEkr48iegchHmf4Zx+NZPfX2M2f5gXCiIv7o8y8JTnIGbAfHza7cErNogJtaPTKX0+pJ/A/wJgCbM3n2897Q6R58boU15wGW9ZyZQb0YuAaCRpJESAmEQuBvjOHannAxXXZkmDO7jmOX2V4orX8H8zw/gg4emncPDbn8BBPBeTGh0nLHYATYPfOdA3pWefgmmNYsg8IBNTosfwRsDwLnLIu9bLkpcOD0SwwnX78W5pqxEnXO84j1dyXH2pGJWgKxkc0F84jKom2ioAsQ/Qv5pFD8D5U9i/vpxZTTmoDTs6O6JxmiApVnh7FkOsJqkJur7tnXCaccaC+d5IHgnMGccuRdjK0LO/cVx3nN+khjQ7T1F58D7ElIpDgLuA56oVChACe/XArvSutox3tNQVwfnjb5KoIdRaRngMCsdUngDCJTUwFIK2r0rg5mjpkY4Z2k2aNTmYN8+pZ6CPKhQiWFmi3j/Qljd5qYj3pX6gL7xFNZD4GjMTnlfWhHqco6tEoUkNS3i/R2DZrnvOrcYaQ9xvAz4FfAq4J1zl3iv2uOPg/nzDSoCdwUEV2DxbeC/fWjhHRA58r0BnV2ezs6Ycjmkrz9guBCDiUIeghByNWLL1pil9wgzeiV2VU2ptkacNFfUZj35YXcC+Okp7S0eGQDnzsl4H52V1p7ao4jVxSKCYaQOYFMcxx8kjucA2VT196WJBZIWAZx8ImTqhErzseifwZqQnYjKyzGtPIjwolAM+dqX6vmvu4fp6vKlwSGrRFFFgatYqYRAVq5AFFqtM6NY9kUI8mbxg0lt34bzRcN70ToB6mpEftimAJPStHccAJi9e4rEacCebJYNEi8lknUA7UB36lU3H6ZGwkknVSU7FaxpVKQsHKIObqx6Cr75rSGg/BzwX8D6OKZa1vapM4vLFU0B1SdqHxckdqfBqntfH3T3Q3ODMbEeOnvFARHqiCYwIQPsdo5u5/hRscjexP5fBDakNykO57ZKIOqrbkcvoPhRsCkQ34hp3cEdXxlOfXfM1VdG/OjWaHZfn58HftWodPVs0OlgK0FLgbbXL+2f2rTbnf7EGk8UJTdFwFdrO/F4ADAz+2gUhkune08M7AgCVC4vl3QH8Eh68jr0BO5bEn/7zW94Pv9FQ0WlwSVKNdAO28wkgM0bA+67P6AwbEyaFBDHEAZi566Ym28ps30Hg4b/rOCOA8jNrCCMnp3UoGnOPJ39TnGl8iPgVmDFeEwgzXTtPDl3NtBEHHelqePaNH0sHelWqeTu+7NLYm6/06AM8uMt4qWlLgeESQW00BeytzNLHEM2Y6x/uczlnyqya5ftE/5TwK9TDz9CwbHgLxAzIN6Wdn5WpVHqDTc0M8DENI66cb7TahZ01taixx9Fko3h9m/kUdGkImp/Nae1zyd5wJYN9VryAScwmdnPgVMOcr+xWldtSm/4uDfKBEfz+960ajJeOtkJ/rZ83vEP10J/N8n9vt9xxLFRrrgxtz6isGpWTElT28whnHHPwZofR6pGvxnjt2YWbNsenpnPx5x3no20p9/AHQkwsXdvloGBZFt1dcbu3RX+/w89vb0uD35Zap7bx+vkfl8AlEDLwOatWRssmjXds+hUG9miGVgmaWmb43XgVFuRXZ1Z+voigiARfvv2Clf/XZGXXwkwi58juem5sspB3oxhvLljAoTPnXBCfMyTy6Blyv5e2pZ2yOdFc5MxdVoSJFRMhK9UjH37ItraA/r7IVcDO3ZW+NYNMS+uEc7xqvf+thSAlw6s673NhvtiJhOm1SDTYHeg676KZswwtbQEOvpo06V/hl56MfleRVPH5pyu/EyoadNMtTlTyyRTXZ0TRHkzewD4v2l7Mcfbf9gZEOq6ryIp0M3/npFZIAh2gvsFuF9CNLRooWnnNqRyqO/ckJVZ4MENQtAP7jVwPwc+D7w/vb0TvhW7fQsm1Uag+7UNNPuSY1+3Q/JA5bfAT4HHgL98cU1w44MPVvjkxwOeXemRrAjxfwKPpjc48mm8P1Jn7e0GAN3Ars5Oay4XRUMDOGd4z0BaLh8ErQHo6YVCwRgcNNLaQkfq5Tf83gz2LTIDn7QOxYQJRhCIlBtX77h8qKkJTn8XDAw6enp8NS7EbySGv10B0OgLJt4nRY00RYySx5119PyYk04M2LpVtG8R4HvT3n3pDx2AelBz4wRh5qhUqmBYLvXiWaA5l4POroDb76qwc6cD/KY0xR34fQLwVviAJnDNzU0QBI7eXlEuQ9redEDBOf+rNWuDBRdcFNPebki+DfRYWmX6gwfAAVEcQ0+v49FlFeIYJdfXEuG8j6/q67NVfX1uCcR7QWuTCg8bU2f4Bz1qnAt+M2d2qPe9N1JNTSTMVgCfTiu2B7LPRqD5EAnOW89a3qJ5Z0BwDdgciDtAK9Lw1vb7dnL/WwCMTrYa0sgw+GZlcG/m+O8BAJMHLQfMrrGsAAAAAElFTkSuQmCC","players":{"max":10000,"online":1805,"sample":[{"id":"00000000-0000-0000-0000-000000000000","name":"§7§m------------------§r §6§lMinecraft Central§r §7§m-------------------"},{"id":"00000000-0000-0000-0000-000000000000","name":"    §cMinigames §7- §6Skyblock §7- §eCreative §7- §2KitPvP §7- §bPrison §7- §dSurvival"},{"id":"00000000-0000-0000-0000-000000000000","name":"                         §dArenaPvP §7- §bUHC §7- §cFactions"},{"id":"00000000-0000-0000-0000-000000000000","name":"§7§m--------------------------------------------------------"},{"id":"00000000-0000-0000-0000-000000000000","name":"  Website: §7- §ahttps://MCCentral.org"},{"id":"00000000-0000-0000-0000-000000000000","name":"  Forums: §7- §ahttps://MCCentral.org/forum"},{"id":"00000000-0000-0000-0000-000000000000","name":"  Vote: §7- §ahttps://MCCentral.org/vote"},{"id":"00000000-0000-0000-0000-000000000000","name":"  Leaderboards: §7- §ahttps://MCCentral.org/leaderboards"},{"id":"00000000-0000-0000-0000-000000000000","name":"  Donate: §7- §ahttps://buy.MCCentral.org"},{"id":"00000000-0000-0000-0000-000000000000","name":"§7§m--------------------------------------------------------"}]},"version":{"name":"1.16.3","protocol":753}}
Server version : 1.16.3 (protocol v753)
Translations file loaded.
Version is supported.
Logging in...
Crypto keys & hash generated.
Checking Session...
Performing request to sessionserver.mojang.com
> POST /session/minecraft/join HTTP/1.1
> Host: sessionserver.mojang.com
> User-Agent: MCC/1.16.3
> Content-Type: application/json
> Content-Length: 433
> Connection: close
> 
> {"accessToken":"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzOGUwYWNiMThiOGUzZDM1Mjc5YzhjNDk1ZjEyNjQyMiIsInlnZ3QiOiIxZGM1MjQ2NWVjMjM0YmFjODZhMGRjNzUxNzAxYzU2MCIsInNwciI6IjhjZjZjYmIxMTk2ZTQ3ZWQ4NDY5YzE4YmNiOTQyOTk0IiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE2MDQzNDU0MjAsImlhdCI6MTYwNDE3MjYyMH0.PY148FhdoEJQJEdkHnGVPBEm3Y4xZlosf78D5QmoGas","selectedProfile":"8cf6cbb1196e47ed8469c18bcb942994","serverId":"-c37ce52b5c2fbc71dcc18755fecf53576a99317"}

< HTTP/1.1 204 No Content
< Connection: close
< Date: Sat, 31 Oct 2020 20:22:43 GMT
< x-minecraft-request-id: c8749409c53f4ab1
< Cache-Control: no-store
< X-Cache: Miss from cloudfront
< Via: 1.1 e67238cd96dfce710846014b9928af62.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: DFW3-C1
< X-Amz-Cf-Id: hiYio36cy5cDypU0K2CFaEEgJaf-5ikemQM-TtRSkxwFSA7OPgVwWg==
< 
< 
Server was successfully joined.
Type '/quit' to leave the server.
Connection has been lost.
Not connected to any server. Use '/help' for help. 
Or press Enter to exit Minecraft Console Client. 
>>424;3R

**Comment by ORelio** [comment] 2020-11-01 13:55
Beware to redact session tokens before posting raw console output, they allow to play Minecraft under your account.
Well, still no luck here because there's nothing between
```
Server was successfully joined.
Type '/quit' to leave the server.
```
and
```
Connection has been lost.
```
This is hard to diagnose, especially when it only happens under Linux with Mono. I can only say that the Pi's ARM version is known for having more issues than the regular x86_64 one 🤔

**Comment by ReinforceZwei** [comment] 2020-11-01 13:56
Wouldn't the CPU and the RAM of the Pi 1 be the issue? Maybe you can monitor the RAM and CPU usage while trying to login.

**Comment by Dependability** [comment] 2020-11-01 15:39
@ReinforceZwei 
I checked the CPU usage, and it was a 100% while running the exe via mono. The ram was still low. 

I feel like this would not be a problem because I remember reading that someone with a Raspberry pi 0 W was able to run Console Client with no major problems.

**Comment by ORelio** [comment] 2020-11-01 15:54
> Wouldn't the CPU and the RAM of the Pi 1 be the issue? Maybe you can monitor the RAM and CPU usage while trying to login.

I was able to run MCC on a Pi 1 model B+ 5 years ago, the only issue I had with Mono were silent disconnections, and some freezes after idling a few hours. Was running Mono v4.x or something, but I guess it should not matter. However, I'd suggest to disable `terrainandmovements` and other non-chat features that were introduced later and use more RAM/CPU.

**Comment by Dependability** [comment] 2020-11-01 16:23
I disabled the chat features, still no fix. I am thinking that it may be the OS I am using right now. I know it has been a long while, but  do you remember the OS you used the pi? I think that because the Raspberry Pi 1 Model B is now a model that has been discontinued, it may not work as well as intended with the latest Raspbian. @ORelio

**Comment by ReinforceZwei** [comment] 2020-11-01 16:33
Perhaps knowing the disconnect reason from the server side could help diagnosis the problem. (timed out or something else?)

**Comment by Dependability** [comment] 2020-11-01 16:58
@ReinforceZwei There is not really a way for me to check that, but I did see that the bot did connect for about 45 secs, and then it gets disconnected. During that time period, you can not see anything in the chat. The only thing you see in the chat is that it disconnected. Sometimes, after it disconnects, you see about 3 - 4 messages from the server. These messages are just chat messages.

**Comment by ReinforceZwei** [comment] 2020-11-01 17:15
Could be the client being not able to respond the keep alive packet (maybe cpu overloaded?) and got disconnected 30 seconds later by the server. Maybe I could try reproducing the problem on my Pi 3B by limiting the cpu clock rate. 🤔

**Comment by ORelio** [comment] 2020-11-01 17:41
> do you remember the OS you used the pi?

Raspbian. Without GUI (CLI + SSH). That was like 5 years ago.

> I did see that the bot did connect for about 45 secs, and then it gets disconnected

A long time before disconnection is definitely linked to MCC struggling with incoming data and failing to respond to keep-alives. Make sure terrain and movements is properly disabled in config because processing initial terrain data on logon is quite CPU-intensive, especially for a first-gen Pi.

**Comment by Dependability** [comment] 2020-11-01 18:23
> A long time before disconnection is definitely linked to MCC struggling with incoming data and failing to respond to keep-alives. Make sure terrain and movements is properly disabled in config because processing initial terrain data on logon is quite CPU-intensive, especially for a first-gen Pi.

It is already disabled, I don't really know what to do. I was thinking that maybe the Gui was part of the problem, but I went into CLI and the same thing happened.

**Comment by milutinke** [comment] 2022-09-17 19:09
Since Mono is no longer used, I suggest using the latest build which requires .NET Core 6
You can find out how to run the MCC on Raspberry in our documentation: https://mccteam.github.io/guide/installation.html

I'll be closing the issue since Mono is no longer used, if you have any problems with the latest build, open a new issue.

**Closed by milutinke** 2022-09-17 19:09 UTC
Labels: a:bug, on:linux, in:connect-to-server, waiting-for:more-info
