### ISSUE TITLE
1.20.4 Support

### ISSUE THREAD

**Issue by minecraft-fff** [MCCTeam/Minecraft-Console-Client#2637] opened 2023-12-31 11:10 UTC
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20.4

### Console Client Version

20231215-238

### Expected Behavior

connect to minecraft server in offline mode

### Actual Behavior

After manually entering the version when joining a server in offline mode, the connection microsoft.com is performed before connecting to the server

### Steps to Reproduce the bug

1. Join a server of unknown version
2.Manually enter the server version

### Device

Laptop

### Operating System

Windows

**Comment by milutinke** [comment] 2024-01-01 12:35
1.20.4 is not supported yet.
I'll implement the support soon.

**Comment by milutinke** [comment] 2024-01-01 12:35
Duplicate of #2638

**Closed by milutinke** 2024-01-01 12:35 UTC
Labels: a:enhancement, a:new-feature
