### ISSUE TITLE
[BUG] /bed sleep does not work when running on arm processors 

### ISSUE THREAD

**Issue by ChongJF** [MCCTeam/Minecraft-Console-Client#2507] opened 2023-05-22 13:29 UTC
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.4

### Console Client Version

Latest

### Expected Behavior

The bot to sleep in a bed

### Actual Behavior

It prints `Result: Succesfully laid in bed!` but the bot never slept in the bed

### Steps to Reproduce the bug

1. Run it on a computer with arm processors
2. Place a bed next to the bot
3. Run /bed sleep 

### Anythings that could help diagnosing the bug

```txt
I tried running it on my laptop with Windows 10 and it works fine.
I also tried running it on a Ubuntu Virtual Machine and it also works fine.
But it does not work when I run it on a Ubuntu VPS with arm processors.
```

### Device

VPS

### Operating System

Linux

**Comment by milutinke** [comment] 2023-05-23 14:46
Not related to ARM architecture, this is a bug in the MCC or the protocol itself.
Duplicate of #2443

**Closed by milutinke** 2023-05-23 14:46 UTC
Labels: a:bug
