### ISSUE TITLE
[BUG]  /useblock won't open chests

### ISSUE THREAD

**Issue by therepower** [MCCTeam/Minecraft-Console-Client#2695] opened 2024-03-04 22:32 UTC
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20.1

### Console Client Version

Latest

### Expected Behavior

I am using /useblock to open chests
output:
[MCC] Useblock at (-28744.5, 123.0, -4689.5) succeeded.

### Actual Behavior

i get
[MCC] Useblock at (-28744.5, 123.0, -4689.5) succeeded.
but the chest won't open

I checked that the coordinates are right and verified it with /blockinfo
> /blockinfo-28744.5 123 -4689.5
[MCC] Block type: Chest

### Steps to Reproduce the bug

1.  Walk in front of a chest
2. Try to open it via /useblock
3.  Nothing happens

### Anythings that could help diagnosing the bug

```txt
Inventory handling and Terrain and Movenents are enabled.
```

### Device

Laptop

### Operating System

Windows

**Comment by Nekiplay** [comment] 2024-03-05 07:06
Need use (BlockPlace)

**Comment by therepower** [comment] 2024-03-05 20:38
> What is your distance from the chest and does the bot look at the chest?

distance is one block.
I tried with /look and had better success chances but still not reliable

**Comment by milutinke** [comment] 2024-03-05 22:08
Duplicate of #2443 , read the previous conversation and bring the discussion to that issue.

**Closed by milutinke** 2024-03-05 22:08 UTC
Labels: a:bug
