### ISSUE TITLE
[Idea] 

### ISSUE THREAD

**Issue by sunny1028** [MCCTeam/Minecraft-Console-Client#1986] opened 2022-04-02 07:56 UTC
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

20220402-14

### Describe your problem

是否考虑把项目从framework 4  升级成 .netcore6？ .netcore 支持跨平台，不使用Mono可以顺利的在Linux服务器上运行；而且.netcore发展的更好。

### Suggest a possible solution

创建新的分支，项目使用.netcore6框架 原生支持windows+linux。 失去Mono的依赖。 

### Minecraft Version

1.16.5

### Device

VPS

### Operating System

Linux

**Comment by ORelio** [comment] 2022-04-02 16:26
Can't read Chinese but I guess your issue is a duplicate of #1313

**Closed** 2022-04-02 16:27 UTC
Labels: rejected:duplicate, a:enhancement, on:linux, in:installation
