### ISSUE TITLE
[BUG] crash

### ISSUE THREAD

**Issue by deosync** [MCCTeam/Minecraft-Console-Client#2159] opened 2022-09-06 14:20 UTC
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.16.5

### Console Client Version

latest

### Expected Behavior

set version to 1.16-1.16.5
and connect to server mc.playrw.ru(shit server)
and you see this 
> Unhandled exception. System.IO.InvalidDataException: Failed to process incoming packet of type JoinGame. (PacketID: 36, Protocol: 754, LoginPhase: False, InnerException: System.InvalidCastException).
 ---> System.InvalidCastException: Unable to cast object of type 'System.Byte' to type 'System.Int32'.
   at MinecraftClient.Mapping.Dimension..ctor(String name, Dictionary`2 nbt)
   at MinecraftClient.Mapping.World.StoreDimensionList(Dictionary`2 registryCodec)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o)
   at System.Threading.Thread.StartCallback()

### Actual Behavior

play with 1.16.5

### Steps to Reproduce the bug

1. set version to 1.16-1.16.5
2.and connect to server mc.playrw.ru(shit server)
3.and you see this 
> Unhandled exception. System.IO.InvalidDataException: Failed to process incoming packet of type JoinGame. (PacketID: 36, Protocol: 754, LoginPhase: False, InnerException: System.InvalidCastException).
 ---> System.InvalidCastException: Unable to cast object of type 'System.Byte' to type 'System.Int32'.
   at MinecraftClient.Mapping.Dimension..ctor(String name, Dictionary`2 nbt)
   at MinecraftClient.Mapping.World.StoreDimensionList(Dictionary`2 registryCodec)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o)
   at System.Threading.Thread.StartCallback()

### Anythings that could help diagnosing the bug

```txt
Minecraft Console Client v1.19.2 - for MC 1.4.6 to 1.19.2 - Github.com/MCCTeam
[MCC] [Settings] Loading Settings from C:\MCC2\MinecraftClient.ini
Resolving mc.playrw.ru...
[MCC] [Translations] No translation file found for en. (Looked 'C:\MCC2\lang\mcc\en.ini'
[MCC] [Translations] No translation file found for system language (ru). (Looked 'C:\MCC2\lang\mcc\ru.ini'
Color test: Your terminal should display [0123456789ABCDEF]: [0123456789ABCDEF]
You chose to run in offline mode.
Success. (session ID: )
Using Minecraft version 1.16.5 (protocol v754)
[MCC] [AutoRelog] Launching with 3 reconnection attempts
[MCC] [AutoRelog] Initializing without a kick message file
[MCC] [ScriptScheduler] Loading tasks from 'C:\MCC2\tasks.ini'
[MCC] [ScriptScheduler] Loaded task:
triggeronfirstlogin: True
 triggeronlogin: False
 triggerontime: False
 triggeroninterval: False
 timevalue:
 timeinterval: 0
 action: ad off
[MCC] [AutoRespond] File not found: 'C:\MCC2\matches.ini'
Translations file loaded.
[MCC] Version is supported.
Logging in...
[MCC] Server is in offline mode.
[MCC] Server was successfully joined.
Type '/quit' to leave the server.
Авторизация » Сессия активна, ввод пароля не требуется
> Unhandled exception. System.IO.InvalidDataException: Failed to process incoming packet of type JoinGame. (PacketID: 36, Protocol: 754, LoginPhase: False, InnerException: System.InvalidCastException).
 ---> System.InvalidCastException: Unable to cast object of type 'System.Byte' to type 'System.Int32'.
   at MinecraftClient.Mapping.Dimension..ctor(String name, Dictionary`2 nbt)
   at MinecraftClient.Mapping.World.StoreDimensionList(Dictionary`2 registryCodec)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o)
   at System.Threading.Thread.StartCallback()

C:\MCC2>
```

### Device

Laptop

### Operating System

Windows

### Server Address (If applicable)

mc.playrw.ru

**Comment by deosync** [comment] 2022-09-06 15:27
problem not fix

**Comment by deosync** [comment] 2022-09-06 15:28
on connect to server grief-116-1 (/grief-116-1)
you crash

**Comment by deosync** [comment] 2022-09-06 15:29
Minecraft Console Client v1.19.2 - for MC 1.4.6 to 1.19.2 - Github.com/MCCTeam
[MCC] [Settings] Loading Settings from C:\MCC2\MinecraftClient.ini
Resolving mc.playrw.ru...
You chose to run in offline mode.
Using Minecraft version 1.16.5 (protocol v754)
[MCC] Version is supported.
Logging in...
[MCC] Server is in offline mode.
[MCC] Server was successfully joined.
Type '/quit' to leave the server.
Авторизация » Сессия активна, ввод пароля не требуется
> Unhandled exception. System.IO.InvalidDataException: Failed to process incoming packet of type JoinGame. (PacketID: 36, Protocol: 754, LoginPhase: False, InnerException: System.Collections.Generic.KeyNotFoundException).
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'minecraft:world_spawn' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MinecraftClient.Mapping.World.SetDimension(String name)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o)
   at System.Threading.Thread.StartCallback()

C:\MCC2>/grief-116-1

**Comment by BruceChenQAQ** [comment] 2022-09-06 15:39
This is another bug, let me check.

**Comment by BruceChenQAQ** [comment] 2022-09-06 16:18
https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/releases/tag/20220907-16
Can you test with this release and is it working now?

**Comment by deosync** [comment] 2022-09-06 16:47
yes his connect to server but his disconect for using cheats (this is my problem)

**Comment by deosync** [comment] 2022-09-06 16:52
not this not my problem

**Comment by deosync** [comment] 2022-09-06 16:54
ye i fix it

**Comment by BruceChenQAQ** [comment] 2022-09-06 17:23
Did you find the reason why MCC was detected as cheating?

**Comment by milutinke** [comment] 2022-09-06 17:43
> Did you find the reason why MCC was detected as cheating?

Could be that he had terrainhandling enabled and not enabled gravity.

**Comment by milutinke** [comment] 2022-09-06 20:02
> Did you find the reason why MCC was detected as cheating?
> 
> ========================================== if i`m on terrainandmovements=true # Uses more ram, cpu, bandwidth but allows you to move around inventoryhandling=true # Toggle inventory handling (beta) this kick me
> 
> can you fix this please

It could be that the server anti cheat does not like MCC.
Can you give us the full kick message?

**Comment by deosync** [comment] 2022-09-06 20:04
ye i change it

**Comment by deosync** [comment] 2022-09-06 20:05
how it work

**Comment by deosync** [comment] 2022-09-06 22:09
> 

Вы были кикнуты за использование читов (translate it to English)
this error not fix
strings in my config VVVV
==================================
mcforge=false                    # Use 'auto', 'false' or 'true'. Force-enabling only works for MC 1.13+.
brandinfo=vanilla                    # Use 'mcc', 'vanilla', or 'none'. This is how MCC identifies itself to the server.

**Comment by milutinke** [comment] 2022-09-06 22:10
Well, we can't do much about it, you will have to contact the owner of the server, their anti cheat probably doesn't allow for custom clients.

**Comment by deosync** [comment] 2022-09-06 22:14
on old version client this work -_-

**Comment by deosync** [comment] 2022-09-06 22:17
it's connected with terrainandmovements=true # Uses more ram, cpu, bandwidth but allows you to move around
inventoryhandling=true # Toggle inventory handling (beta)

**Comment by BruceChenQAQ** [comment] 2022-09-07 05:55
Tested multiple releases and confirmed that the issue occurs between [20220506-20 and 20220816-25](https://github.com/MCCTeam/Minecraft-Console-Client/compare/20220506-20...20220816-25)

**Comment by BruceChenQAQ** [comment] 2022-09-07 10:32
The latest version has improved handling of gravity, which may be able to solve this issue. (I have not tested).

**Comment by unitythemaker** [comment] 2022-09-15 03:05
Same here
Tried so many combinations and this is another one:
> ./MinecraftClient --terrainandmovements=true --brandinfo=vanilla player_name - ip_addr
> Unhandled exception. System.IO.InvalidDataException: Failed to process incoming packet of type JoinGame. (PacketID: 37, Protocol: 760, LoginPhase: False, InnerException: System.Collections.Generic.KeyNotFoundException).
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'minecraft:skyblock_lobby' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MinecraftClient.Mapping.World.SetDimension(String name)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o)
   at System.Threading.Thread.StartCallback()
fish: “./MinecraftClient --terrainandm…” terminated by signal SIGABRT (Abort)

It looks like MultiVerse is the problem: "The given key 'minecraft:skyblock_lobby' was not present in the dictionary."
I didn't inspect the codes but in my opinion if there is a way that dictionary checker for dimensions should be removed.

**Comment by BruceChenQAQ** [comment] 2022-09-15 04:36
> It looks like MultiVerse is the problem: "The given key 'minecraft:skyblock_lobby' was not present in the dictionary." I didn't inspect the codes but in my opinion if there is a way that dictionary checker for dimensions should be removed.

Are you running the latest release?
Can you provide the server address and the steps to reproduce this error?
(This error occurs when the corresponding dimension is not found when setting the current dimension.)

**Comment by unitythemaker** [comment] 2022-09-15 11:19
> > It looks like MultiVerse is the problem: "The given key 'minecraft:skyblock_lobby' was not present in the dictionary." I didn't inspect the codes but in my opinion if there is a way that dictionary checker for dimensions should be removed.
> 
> Are you running the latest release? Can you provide the server address and the steps to reproduce this error? (This error occurs when the corresponding dimension is not found when setting the current dimension.)
> 
> Tried to fix this issue on [BruceChenQAQ@a2b2aeb](https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/commit/a2b2aeb748442308cfb44368016be06f879dc613) ([Release](https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/releases/tag/20220915-33)). Since I don't have the server address to take the test, I can't confirm if it's caused by this bug.

Yeah I tried on this version: [20220913-58: Upgrade Auto Fishing](https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20220913-58)
The new error after using this release  is: [20220915-33](https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/releases/tag/20220915-33)
> Unhandled exception. System.IO.InvalidDataException: Failed to process incoming packet of type EntityMetadata. (PacketID: 80, Protocol: 760, LoginPhase: False, InnerException: System.IO.InvalidDataException).
 ---> System.IO.InvalidDataException: Unknown Metadata Type ID 22. Is this up to date for new MC Version?
   at MinecraftClient.Protocol.Handlers.DataTypes.ReadNextMetadata(Queue`1 cache, ItemPalette itemPalette)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o)
   at System.Threading.Thread.StartCallback()
fish: “./MinecraftClient --inventoryha…” terminated by signal SIGABRT (Abort)

Server address is ``play.mine.tc`` and the recommended version is 1.18.2 and 1.19.2. It's a Turkish server which runs on Flamecord and joinable with Bedrock Edition using Geyser (``bedrock.mine.tc``). You need to join the server than register via ``/reg <pass> <pass>`` then ``/skyblock`` to enter the SkyBlock server.

**Comment by BruceChenQAQ** [comment] 2022-09-15 13:17
> Yeah I tried on this version: [20220913-58: Upgrade Auto Fishing](https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20220913-58) The new error after using this release is: [20220915-33](https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/releases/tag/20220915-33)
> 
> > Unhandled exception. System.IO.InvalidDataException: Failed to process incoming packet of type EntityMetadata. (PacketID: 80, Protocol: 760, LoginPhase: False, InnerException: System.IO.InvalidDataException).
> > ---> System.IO.InvalidDataException: Unknown Metadata Type ID 22. Is this up to date for new MC Version?
> > at MinecraftClient.Protocol.Handlers.DataTypes.ReadNextMetadata(Queue`1 cache, ItemPalette itemPalette)    at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
> > --- End of inner exception stack trace ---
> > at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
> > at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o)
> > at System.Threading.Thread.StartCallback()
> > fish: “./MinecraftClient --inventoryha…” terminated by signal SIGABRT (Abort)
> 
> Server address is `play.mine.tc` and the recommended version is 1.18.2 and 1.19.2. It's a Turkish server which runs on Flamecord and joinable with Bedrock Edition using Geyser (`bedrock.mine.tc`). You need to join the server than register via `/reg <pass> <pass>` then `/skyblock` to enter the SkyBlock server.

Should be fixed in https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/commit/c00468c1036fa2f7658c57da83df2efbcd8df22a ([Release](https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/releases/tag/20220915-34)).
I joined the sky block server and created my island and it works fine.

**Comment by unitythemaker** [comment] 2022-09-15 22:17
It's fixed thank you very much!

**Closed** 2022-09-17 20:07 UTC
Labels: a:bug, waiting-for:more-info, in:terrain-handling
