### ISSUE TITLE
[Idea] 1.19.3

### ISSUE THREAD

**Issue by UsainSrht** [MCCTeam/Minecraft-Console-Client#2384] opened 2022-12-18 18:51 UTC
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

GitHub build 176, built on 2022-12-02 from commit 597af24

### Describe your problem

1.19.3

### Minecraft Version

1.19.3

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment] 2022-12-19 23:55
Already being worked on.

**Comment by agitationswapping** [comment] 2023-01-06 19:21
Any update on the progress/timeline and/or difficulties being faced?

Is there a candidate version that has chat only anywhere?

Apologize if this information is already somewhere else. Thanks so much for all your hard work!

**Comment by JIBSIL** [comment] 2023-01-07 01:22
> Any update on the progress/timeline and/or difficulties being faced?
> 
> Is there a candidate version that has chat only anywhere?
> 
> Apologize if this information is already somewhere else. Thanks so much for all your hard work!

It was partially completed in this PR: #2393 

I don't think the chat part is fully complete yet though.

**Comment by BruceChenQAQ** [comment] 2023-01-07 09:10
I'm working on extracting the protocol processing library from MCC into a separate repository, and I'll probably work on adapting 1.19.3 after I'm done with that, otherwise I may have to deal with this part of the code twice.

There is still a problem that we need to wait for the merge of https://github.com/MCCTeam/Minecraft-Console-Client/pull/2358 and https://github.com/breadbyte/ConsoleInteractive/pull/20. Since #2393 is developed based on the master branch and the latest build is based on the brigadier-dev branch, we need to wait for the brigadier-dev branch to be merged into the master branch. (breadbyte may have been busy recently and he hasn't reviewed pull request https://github.com/breadbyte/ConsoleInteractive/pull/20 yet.)

**Comment by milutinke** [comment] 2023-01-14 16:00
1.19.3 is out in a pre-release

**Closed by milutinke** 2023-01-14 16:00 UTC
Labels: a:enhancement, a:new-feature

**Comment by JIBSIL** [comment] 2023-01-19 01:16
> 1.19.3 is out in a from of a pre-release

It appears that chat signing is not functional in the pre-release (or it could be my settings). Testing on a 1.19.3 PaperSpigot server, no plugins, online mode + enforce-secure-profile on.

**Comment by BruceChenQAQ** [comment] 2023-01-19 05:40
> > 1.19.3 is out in a from of a pre-release
> 
> It appears that chat signing is not functional in the pre-release (or it could be my settings). Testing on a 1.19.3 PaperSpigot server, no plugins, online mode + enforce-secure-profile on.

Can you provide us with the server address so we can test the issue?

**Comment by JIBSIL** [comment] 2023-01-19 19:46
> > > 1.19.3 is out in a from of a pre-release
> > 
> > 
> > It appears that chat signing is not functional in the pre-release (or it could be my settings). Testing on a 1.19.3 PaperSpigot server, no plugins, online mode + enforce-secure-profile on.
> 
> Can you provide us with the server address so we can do more test on the issue?

Sure, try chatting on minehut.com (you get kicked)

**Comment by BruceChenQAQ** [comment] 2023-01-20 17:52
> > > > 1.19.3 is out in a from of a pre-release
> > > 
> > > 
> > > It appears that chat signing is not functional in the pre-release (or it could be my settings). Testing on a 1.19.3 PaperSpigot server, no plugins, online mode + enforce-secure-profile on.
> > 
> > 
> > Can you provide us with the server address so we can do more test on the issue?
> 
> Sure, try chatting on minehut.com (you get kicked)

We have received feedback that MCC's message signatures are not working properly on this server, but testing with multiple accounts from three developers has failed to reproduce the issue.

**Comment by JIBSIL** [comment] 2023-01-22 02:48
> > > > > 1.19.3 is out in a from of a pre-release
> > > > 
> > > > 
> > > > It appears that chat signing is not functional in the pre-release (or it could be my settings). Testing on a 1.19.3 PaperSpigot server, no plugins, online mode + enforce-secure-profile on.
> > > 
> > > 
> > > Can you provide us with the server address so we can do more test on the issue?
> > 
> > 
> > Sure, try chatting on minehut.com (you get kicked)
> 
> We have received feedback that MCC's message signatures are not working properly on this server, but testing with multiple accounts from three developers has failed to reproduce the issue.

Strange. Are you (and the other devs) using the latest, x64 windows release?

**Comment by JIBSIL** [comment] 2023-01-23 18:42
Given issues like [CommandAPI/311](https://github.com/JorelAli/CommandAPI/issues/311) and [ItemsAdder/1961](https://github.com/PluginBugs/Issues-ItemsAdder/issues/1961) it appears that chat preview is the source of this kick message. I'd make an educated guess that the protocol on chat preview changed; Minehut (iirc) uses chat preview to modify messages before sending for commands like /ad, while keeping signatures intact.

**Comment by BruceChenQAQ** [comment] 2023-01-24 11:24
> Given issues like [CommandAPI/311](https://github.com/JorelAli/CommandAPI/issues/311) and [ItemsAdder/1961](https://github.com/PluginBugs/Issues-ItemsAdder/issues/1961) it appears that chat preview is the source of this kick message. I'd make an educated guess that the protocol on chat preview changed; Minehut (iirc) uses chat preview to modify messages before sending for commands like /ad, while keeping signatures intact.
> 
> To be clear: this relates to the "Chat message validation failure" issue when sending the /ad command; chatting outputs a different error message

In 1.19.3, MoJang has completely removed the ChatPreview packet. That doesn't seem to be the issue.

And I did test with the latest x64 windows release.

**Comment by BruceChenQAQ** [comment] 2023-01-29 14:44
> > > > 1.19.3 is out in a from of a pre-release
> > > 
> > > 
> > > It appears that chat signing is not functional in the pre-release (or it could be my settings). Testing on a 1.19.3 PaperSpigot server, no plugins, online mode + enforce-secure-profile on.
> > 
> > 
> > Can you provide us with the server address so we can do more test on the issue?
> 
> Sure, try chatting on minehut.com (you get kicked)

Try the latest release, which may fix this issue.

**Comment by JIBSIL** [comment] 2023-01-30 00:49
It fixes the issue only for chat. Commands still have the issue

**Comment by DereWah** [comment] 2023-02-14 19:10
> > > > > 1.19.3 is out in a from of a pre-release
> > > > 
> > > > 
> > > > It appears that chat signing is not functional in the pre-release (or it could be my settings). Testing on a 1.19.3 PaperSpigot server, no plugins, online mode + enforce-secure-profile on.
> > > 
> > > 
> > > Can you provide us with the server address so we can do more test on the issue?
> > 
> > Sure, try chatting on minehut.com (you get kicked)
> 
> Try the latest release, which may fix this issue.

I've been having the same issue on and off both with messages and commands. Sometimes when I join I'm able to speaj / send commands, but after some time it bugs and starts kicking after any chat interaction.

Other times as soon as I join I have issues with chat and instantly get kicked after typing anything (both commands and messages)
