### ISSUE TITLE
[Idea] 1.8 Entity

### ISSUE THREAD

**Issue by IsaacJuracich** [MCCTeam/Minecraft-Console-Client#1823] opened 2021-11-15 20:41 UTC
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

1.8 Entity Data | A lot of people who use this client are using it for factions on 1.8 and 1.8.9. It'd make a lot easier to have entity tracking within the bot, as most servers dont allow 1.9+.

### Suggest a possible solution

Adding 1.8 Entity Palette. 

### Minecraft Version

1.8

**Comment by milutinke** [comment] 2022-09-17 19:55
Duplicate of #1523

**Closed by milutinke** 2022-09-17 19:55 UTC
Labels: a:enhancement, a:new-feature
