### ISSUE TITLE
Captcha when logging in to the server

### ISSUE THREAD

**Issue by 0RGAZM** [MCCTeam/Minecraft-Console-Client#1956] opened 2022-03-02 15:06 UTC
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

The last

### Describe your problem

There is a problem when logging into the server. On the server, uponentering it, it asks you to enter the code from the picture, and this is the whole problem.

Can anyone help with solving this problem

### Attach screenshot here (If applicable)

![FOabOmco_rU](https://user-images.githubusercontent.com/100783010/156388046-756b55af-9470-479e-8eab-a84d55789fb6.jpg)

### Minecraft Version

1.12.2

### Device

Laptop

### Operating System

Windows

**Comment by ORelio** [comment] 2022-03-06 19:22
Looks like a duplicate of #1597 - Maps are not handled for now.

**Closed** 2022-03-06 19:22 UTC
Labels: rejected:duplicate, a:new-feature, in:protocol-compatibility
