### ISSUE TITLE
[Idea] 1.21

### ISSUE THREAD

**Issue by BreadNotDuck** [MCCTeam/Minecraft-Console-Client#2818] opened 2024-11-26 21:59 UTC
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [x] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

Please add 1.21 version

### Suggest a possible solution

-

### Attach screenshot here (If applicable)

-

### Minecraft Version

1.21

### Device

Desktop

### Operating System

Windows

**Comment by breadbyte** [comment] 2024-12-25 02:18
Duplicate of #2738.

Work in progress code can be built from source at https://github.com/milutinke/Minecraft-Console-Client/tree/1.20.6.

If you don't want to build from source, you can use an alternative build here: 
https://github.com/Robert-Kidder/Minecraft-Console-Client/releases/tag/20241026-9

**Closed by breadbyte** 2024-12-25 02:18 UTC
Labels: a:enhancement, a:new-feature
