### ISSUE TITLE
[Idea] 1.19

### ISSUE THREAD

**Issue by HughSparks** [MCCTeam/Minecraft-Console-Client#2053] opened 2022-06-20 06:15 UTC
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

1.19 support. Not much has changed as far as I know so its probably a hard coded prevention.

### Minecraft Version

1.19

### Device

Raspberry Pi

### Operating System

Linux

**Comment by UsainSrht** [comment] 2022-06-28 19:15
any ETA?

**Comment by ORelio** [comment] 2022-06-28 23:19
We are a small team and lacking time to work on updates so it'll arrive eventually but no ETA.
Of course, contributions are welcome!
See also https://github.com/MCCTeam/Minecraft-Console-Client/issues/1629 for 1.17 status.

(Everything is implemented for 1.16, only basic support above that version)

**Comment by HughSparks** [comment] 2022-07-01 00:50
TBH I only really need the client to connect and stand there

**Comment by HughSparks** [comment] 2022-07-01 09:02
> 

Thank you so much!!! I can barely read basic C so your work is a god send thank you so much!!

**Comment by ORelio** [comment] 2022-07-01 11:37
Hey @milutinke, thanks for working on this. If they actually did change every packet and even the cryptography stuff, maybe creating a whole new protocol handler like Protocol119.cs would be appropriate?

**Comment by ORelio** [comment] 2022-07-01 11:39
... In that case you could have a separate packet type enum, yes

**Comment by milutinke** [comment] 2022-07-01 13:47
I'll most likely do that.
Regarding the branch, can we get a 1.19 branch since I probably can't do every single part of the code, but someone else could help out, it's less likely that they would notice my fork and my branch than if it was on here?
I'll try to implement as much as I can, but never worked with Crypto stuff, I'll might need some help from someone else.

**Comment by milutinke** [comment] 2022-07-01 20:00
Made some good progress today: 
https://github.com/milutinke/Minecraft-Console-Client/commit/401d1f16b8cd0002a13fa2febc3aa41311f91f2e
Almost all packets are implemented except the new chat ones.

**Comment by milutinke** [comment] 2022-07-04 11:22
@HughSparks Making some progress.
Got the bot to connect, tested `/respawn`, it works, he can be online.
Basically almost every packet except Chat ones have been implemented (tho not tested).
So if you want you can help me test our stuff.
You can fork and build https://github.com/milutinke/Minecraft-Console-Client/commit/cca4de179951ed22b9a43fa2a04fbbe03520fad6

**Comment by milutinke** [comment] 2022-07-04 11:52
Current progress:
![image](https://user-images.githubusercontent.com/441903/177149423-dd295d28-399e-403b-9947-fcaa12c287ed.png)

**Comment by HughSparks** [comment] 2022-07-04 20:01
@milutinke you are amazing!! Thank you so much.

**Comment by milutinke** [comment] 2022-07-04 22:36
Found this nice flow chart for 1.19 protocol, the things are now a bit clearer.
Now I have figure out how to generate Sha256 with RSA key pairs in C# without any libraries.
![image](https://user-images.githubusercontent.com/441903/177222279-47d7e9e3-48f8-4d4d-9f00-5f9b7a02626e.png)

**Comment by HughSparks** [comment] 2022-07-05 05:30
Thanks for your help... Just so you know I tried to build it and when I atempt to connect it the client hangs then times out.
`Minecraft Console Client v1.19 - for MC 1.4.6 to 1.19 - Github.com/MCCTeam
[MCC] [Settings] Loading Settings from D:\Users\hugh\Downloads\Minecraft-Console-Client-81f33d3ead8529a02b3a6fb49f1fd8633eedb0e6\Minecraft-Console-Client-81f33d3ead8529a02b3a6fb49f1fd8633eedb0e6\MinecraftClient\bin\Debug\MinecraftClient.ini
Connecting to Microsoft...
Retrieving Server Info...
Server version : 1.19 (protocol v759)
Downloading 'en_GB.lang' from Mojang servers...
Failed to download the file.
Translations file not found: 'lang\en_GB.lang'
Some messages won't be properly printed without this file.
[MCC] Version is supported.
Logging in...
[MCC] >> Initiating a handshake with the server: System.Byte[]
[MCC] >> Handshake established, sending a login packet: System.Byte[]
[MCC] >> Encryption request:  = System.Byte[] - System.Byte[]
[MCC] Checking Session...
[MCC] Connection has been lost.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.
>`

**Comment by milutinke** [comment] 2022-07-05 06:36
> Thanks for your help... Just so you know I tried to build it and when I atempt to connect it the client hangs then times out. `Minecraft Console Client v1.19 - for MC 1.4.6 to 1.19 - Github.com/MCCTeam [MCC] [Settings] Loading Settings from D:\Users\hugh\Downloads\Minecraft-Console-Client-81f33d3ead8529a02b3a6fb49f1fd8633eedb0e6\Minecraft-Console-Client-81f33d3ead8529a02b3a6fb49f1fd8633eedb0e6\MinecraftClient\bin\Debug\MinecraftClient.ini Connecting to Microsoft... Retrieving Server Info... Server version : 1.19 (protocol v759) Downloading 'en_GB.lang' from Mojang servers... Failed to download the file. Translations file not found: 'lang\en_GB.lang' Some messages won't be properly printed without this file. [MCC] Version is supported. Logging in... [MCC] >> Initiating a handshake with the server: System.Byte[] [MCC] >> Handshake established, sending a login packet: System.Byte[] [MCC] >> Encryption request: = System.Byte[] - System.Byte[] [MCC] Checking Session... [MCC] Connection has been lost. Not connected to any server. Use '/help' for help. Or press Enter to exit Minecraft Console Client. `

Can you enable the debug mode?
I think it's an issue with login, maybe Mojang/Microsoft API can't be reached.
I've tested this with an offline account and an offline server.
![image](https://user-images.githubusercontent.com/441903/177264443-d28a6977-87d7-4516-9b14-fd18a2925587.png)

**Comment by milutinke** [comment] 2022-07-05 07:44
@HughSparks Fixed, I've accidentally reordered items being sent in the Encryption Request.
Clone the newest version of 1.19 branch and try it out. 
I've tested it with online-mode, works.

![image](https://user-images.githubusercontent.com/441903/177276407-0986b1be-2563-4320-917e-d99101862af8.png)

**Comment by milutinke** [comment] 2022-07-05 09:04
Current progress:
- Implemented Player Chat Packet
- Implemented Chat Preview Packet
- Implemented System Message Packet

I'm successfully receiving System Messages, but through Player Chat Packet, not System Messages.
Chat Preview was not received a single time.
And Player Chat Packet does not get messages from other players for some reason.
I think this might be because of `enforce-secure-profile` property in `server.properties` being disabled.
I've not yet implemented `enforce-secure-profile`.
The test was done on an `online-mode` set to `true`.

![image](https://user-images.githubusercontent.com/441903/177291372-03a94fb1-a7b0-4155-8f60-4e50da9942a5.png)

**Comment by milutinke** [comment] 2022-07-05 10:58
Update.
I've found about this `https://api.minecraftservices.com/player/certificates`
So basically we need to fetch public and private keys from Mojang when we log in via Microsoft, otherwise, we will probably have to generate our own.

I've added a code which does fetching, but I need to implement verification and serialization.

**Comment by Splarkszter** [comment] 2022-07-15 12:30
Thanks!!! i will test it.

**Comment by Splarkszter** [comment] 2022-07-15 12:40
Oh wow. this is awesome. i can run multiple accounts, null RAM usage and it can respawn without issues. Love it. many many thanks!!!!!

**Comment by kqfflo** [comment] 2022-07-15 13:12
Yeah, AFK plugins might be a an issue at the moment. However,I see a lot of progress regarding network packets. Maybe it will not take too long for a real release for 1.19. I play on our own infrastructure so having no trouble with that ;)

**Comment by milutinke** [comment] 2022-07-15 22:52
I got overloaded with work, I'll continue updating when I can.
For anyone needing a half functional implementation you can build from my 1.19 branch: https://github.com/milutinke/Minecraft-Console-Client

**Comment by milutinke** [comment] 2022-07-15 22:55
Currently this is the state of the implementation

![Screenshot_20220716-005231_GitHub.jpg](https://user-images.githubusercontent.com/441903/179321754-dec32b8a-5457-45c3-93fe-3dd9c9dc3d9c.jpg)

**Comment by ZizzyDizzyMC** [comment] 2022-07-22 18:45
@milutinke I wanted to tell you thank you for the work, do you have a link in which I could buy you a coffee (or 5)?

While I'm unable to balance life and multiple projects I always want to see MCC succeed, and you're doing great work.

Question, will these updates also bring about better support for versions below 1.19 as well? IIRC 1.16 was complete but 1.17 onward was only partial support.

**Comment by milutinke** [comment] 2022-07-22 19:08
> @milutinke I wanted to tell you thank you for the work, do you have a link in which I could buy you a coffee (or 5)?
> 
> While I'm unable to balance life and multiple projects I always want to see MCC succeed, and you're doing great work.
> 
> Question, will these updates also bring about better support for versions below 1.19 as well? IIRC 1.16 was complete but 1.17 onward was only partial support.

If you really want, to you can find my donation info here: https://github.com/milutinke/sqcp

As for supporting inventories and entity handling, I've done that in my main branch, but I've encountered a bug with NBT data being set, which I've yet to resolve, I need to dig deeper into the code base for NBT and the specification, maybe if you're familiar with it you could take a look. (Pull request: https://github.com/MCCTeam/Minecraft-Console-Client/pull/1943)

**Comment by Sergz69** [comment] 2022-07-22 22:22
You my friend, are a legend to the community. I thank you!

**Comment by milutinke** [comment] 2022-07-23 15:56
Notes for myself and others:

For https://wiki.vg/Protocol#Chat_Message packet, so we need basically to create a X509 compatible signature that needs to include:
- Player's private key
- Salt (this could be a random long integer)
- most significant bit of player's UUID
- least significant bit of playe's UUID
- time in epoch
- JSON formatted chat message that has been converted to a UTF-8 byte array

Update on the progress:
So I've tested the keys obtaining API, working as intended, now I have to find out how I can generate the signature above (for Mojang accounts), and how I can generate a RSA X509 key pair in form of a string in C#, if anyone has experience with this, you can send the code here.

**Comment by milutinke** [comment] 2022-07-23 18:06
Anyone has any idea how to convert RSA Public key from a string to a byte array in C#?
![image](https://user-images.githubusercontent.com/441903/180617537-b9f29cba-7f28-49ac-a49a-b9d3898d6da0.png)

This code above is not working
![image](https://user-images.githubusercontent.com/441903/180617558-ef90367a-7472-4399-89fa-d3359c523ed2.png)

**Comment by milutinke** [comment] 2022-07-23 19:33
Anyone got any ideas?
![image](https://user-images.githubusercontent.com/441903/180620269-a1d1147b-4140-4b5b-8c1e-8bf67a8dda90.png)

**Comment by BruceChenQAQ** [comment] 2022-07-26 13:53
@milutinke 

Here is a millisecond timestamp(13 numbers)
```C#
private static long ConvertToTimestamp(DateTime value)
{
    TimeSpan elapsedTime = value - Epoch;
    return (long)elapsedTime.TotalSeconds;
}
👇
private static long ConvertToTimestamp(DateTime value)
{
    return (long)(value - Epoch).TotalMilliseconds;
}
```

UTC is required
```C#
long timestamp = (long)ConvertToTimestamp(DateTime.Parse(keysInfo.ExpiresAt));
👇
long timestamp = ConvertToTimestamp(DateTime.Parse(keysInfo.ExpiresAt).ToUniversalTime());
```

In .NET 5, it would be easier to import keys in PEM format for message signing, perhaps consider upgrading first?

**Comment by Ege9** [comment] 2022-07-26 18:05
Hi guys. I've read everything you wrote, but I'm very confused. Did you make a working version of the console client in 1.19?

**Comment by milutinke** [comment] 2022-07-26 20:38
> @milutinke 
> 
> Here is a millisecond timestamp(13 digits)
> ```C#
> private static long ConvertToTimestamp(DateTime value)
> {
>     TimeSpan elapsedTime = value - Epoch;
>     return (long)elapsedTime.TotalSeconds;
> }
> 👇
> private static long ConvertToTimestamp(DateTime value)
> {
>     return (long)(value - Epoch).TotalMilliseconds;
> }
> ```
> ---
> UTC is required
> ```C#
> long timestamp = (long)ConvertToTimestamp(DateTime.Parse(keysInfo.ExpiresAt));
> 👇
> long timestamp = ConvertToTimestamp(DateTime.Parse(keysInfo.ExpiresAt).ToUniversalTime());
> ```
> ---
> In .NET 5, it would be easier to import keys in PEM format for message signing, perhaps consider upgrading first?
> (currently working on https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/commits/master)

I'll take a look tomorrow.
Thanks

**Comment by milutinke** [comment] 2022-07-26 20:40
> Hi guys. I've read everything you wrote, but I'm very confused. Did you make a working version of the console client in 1.19?

It's half functional, you can only connect to servers without `enforce-secure-profile` set to `false` and just stand. You can't even recieve or send messages (you can only get system messages from the server).

**Comment by Ege9** [comment] 2022-07-27 06:56
> 

Okay, i want to use it. Could you please tell me how to download it?

**Comment by milutinke** [comment] 2022-07-27 08:17
> > 
> 
> Okay, i want to use it. Could you please tell me how to download it?

Binary download (Compiled on Windows 10 Pro 21H2 - 64 bit):
https://www.sendspace.com/file/itjngi

If you want to build it yourself, go to https://github.com/milutinke/Minecraft-Console-Client/tree/1.19
And follow the build instructions from the description.

**Comment by Ege9** [comment] 2022-07-27 09:50
The client closes after giving this error. Can someone help please
![Screenshot (116)](https://user-images.githubusercontent.com/110056150/181218072-884f591e-494c-4a2d-b1b6-0ff768aa7529.png)
?

**Comment by milutinke** [comment] 2022-07-27 09:56
> The client closes after giving this error. Can someone help please ![Screenshot (116)](https://user-images.githubusercontent.com/110056150/181218072-884f591e-494c-4a2d-b1b6-0ff768aa7529.png) ?

Only Microsoft login works currently.
We don't have a way to generate keys currently.

**Comment by milutinke** [comment] 2022-07-27 10:11
@Ege9 Try now: https://www.sendspace.com/file/cyuqkg
I've fixed the thing, so offline account should work now.

**Comment by Ege9** [comment] 2022-07-27 12:28
> @Ege9 Try now: https://www.sendspace.com/file/cyuqkg I've fixed the thing, so offline account should work now.
This only works when I first open the file. Then it keeps giving the same error again.

**Comment by Ege9** [comment] 2022-07-27 12:30
> @Ege9 Try now: https://www.sendspace.com/file/cyuqkg I've fixed the thing, so offline account should work now.

Windows found trojan in it, is this normal?

**Comment by BruceChenQAQ** [comment] 2022-07-27 16:22
<img width="895" alt="2022-07-28_001034" src="https://user-images.githubusercontent.com/26017411/181296782-db8846eb-3299-4ff1-97db-b26735a7c8ba.png">

finally, it works

Using built-in librarie: [RSA.SignData Method](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsa.signdata?view=net-5.0)

(still a lot of bugs need to be fixed)

**Comment by milutinke** [comment] 2022-07-27 23:19
> > @Ege9 Try now: https://www.sendspace.com/file/cyuqkg I've fixed the thing, so offline account should work now.
> 
> Windows found trojan in it, is this normal?

It is normal, because the exe was not signed with a certificate, and Windows defender is just bad.
You can compile it yourself if you're worried, the build instructions are in the bottom of README.md

**Comment by milutinke** [comment] 2022-07-27 23:26
> <img width="895" alt="2022-07-28_001034" src="https://user-images.githubusercontent.com/26017411/181296782-db8846eb-3299-4ff1-97db-b26735a7c8ba.png">
> 
> finally, it works
> 
> Using built-in librarie: [RSA.SignData Method](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsa.signdata?view=net-5.0)
> 
> (still a lot of bugs need to be fixed)

Awesome.
I haven't found about it, tho haven't had much time to do a research outside of the protocol.
I'm new to C# ecosystem too, not familiar with everything yet.
Thank you a lot for helping out.

**Comment by Ege9** [comment] 2022-07-28 07:16
It doesn't work offline, sadly. I don't know if i should change something in the config file.

**Comment by milutinke** [comment] 2022-07-28 15:03
> It doesn't work offline, sadly. I don't know if i should change something in the config file.

For me it worked fine, I've tested before compiling.

**Comment by milutinke** [comment] 2022-07-29 13:18
Note to myself and others, in 1.19.1, we will need to send player UUID in a Login Start packet, after the public key, this is not yet on wiki.

**Comment by BruceChenQAQ** [comment] 2022-07-29 14:04
<img width="1614" alt="2022-07-29_220247" src="https://user-images.githubusercontent.com/26017411/181776988-165e835b-5bad-4a3e-ab0a-d1cf0925a36f.png">

basic support for 1.19: https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/commit/e1b4d8f344c1ad7cadf3fe4381d3bc8acb1053c5

Still does not work properly on servers in online mode (due to https://github.com/MCCTeam/Minecraft-Console-Client/issues/2082)

**Comment by Saidas25** [comment] 2022-07-30 17:25
how to fix this: it kicks me after i say anything in chat or type a command
[MCC] Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(28) + length(8) exceeds writerIndex(28): PooledUnsafeDirectByteBuf(ridx: 28, widx: 28, cap: 28)

**Comment by milutinke** [comment] 2022-07-30 18:29
> how to fix this: it kicks me after i say anything in chat or type a command [MCC] Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(28) + length(8) exceeds writerIndex(28): PooledUnsafeDirectByteBuf(ridx: 28, widx: 28, cap: 28)

Which build are you using?
The one I provided few days ago is outdated, use the https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/commit/e1b4d8f344c1ad7cadf3fe4381d3bc8acb1053c5

**Comment by Saidas25** [comment] 2022-07-30 19:05
where do i find the download

**Comment by Saidas25** [comment] 2022-07-30 19:13
im soo confused cant find any downloads

**Comment by Saidas25** [comment] 2022-07-30 19:33
this place is soo confusing :(

**Comment by milutinke** [comment] 2022-07-30 20:56
> this place is soo confusing :(

You need to build the solution yourself using Visual Studio Code or MSBuild.
You have instructions on how to build it in the README.md
Or you can ask someone to build it for you.
I would, but I do not have the tooling available currently.

**Comment by BruceChenQAQ** [comment] 2022-07-31 02:49
Pull requests are waiting to be merged: https://github.com/MCCTeam/Minecraft-Console-Client/pull/2084

@Saidas25 You can find the built binaries here
https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/releases/tag/1.19

(Not familiar with how to build in .NET 5, generates large files.)

**Comment by Saidas25** [comment] 2022-07-31 08:03
thank you @BruceChenQAQ i looked everywhere but did not find this

**Comment by Saidas25** [comment] 2022-07-31 09:03
ok tried that one it does not even open it opens and after 0.1secs closes

**Comment by milutinke** [comment] 2022-07-31 09:52
> Pull requests are waiting to be merged: #2084
> 
> @Saidas25 You can find the built binaries here https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/releases/tag/1.19
> 
> (Not familiar with how to build in .NET 6, generates large files.)

If I'm not mistaken, `dotnet publish MinecraftClient -r win-x64 -p:PublishSingleFile=true`

**Comment by Saidas25** [comment] 2022-07-31 10:09
can someone help me build it im stuck on Edit MinecraftClient.csproj to set the Build target to Release on [line 4]
i came here for MCC 1.19 but got a headache instead

**Comment by breadbyte** [comment] 2022-07-31 10:13
> > Pull requests are waiting to be merged: #2084
> > @Saidas25 You can find the built binaries here https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/releases/tag/1.19
> > (Not familiar with how to build in .NET 6, generates large files.)
> 
> Awesome. If I'm not mistaken for a single binary, `dotnet publish MinecraftClient -f net6.0 -r win-x64 -p:PublishSingleFile=true` Can't try right now because I don't have the environment for .NET

The complete build args should be `dotnet publish MinecraftClient -f net6.0 -r win-x64 --no-self-contained -c Release -p:UseAppHost=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=None` to compile only an exe without any other dlls.

The flags are what i used for the automated builds in https://github.com/MCCTeam/Minecraft-Console-Client/pull/2059

**Comment by BruceChenQAQ** [comment] 2022-07-31 11:41
> ok tried that one it does not even open it opens and after 0.1secs closes

Do you have the .NET runtime installed?

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=6.0.7

**Comment by Saidas25** [comment] 2022-07-31 12:03
thank you it finally works i joined the server i wanted now i can use my guardian farm

**Comment by madoiscool** [comment] 2022-08-08 16:53
can anyone made a working version for 1.19.1 or 1.19.2 yet?

**Comment by Splarkszter** [comment] 2022-08-08 18:18
> can anyone made a working version for 1.19.1 or 1.19.2 yet?

being realistic i think no one is using those versions XD

**Comment by madoiscool** [comment] 2022-08-08 22:16
> > can anyone made a working version for 1.19.1 or 1.19.2 yet?
> 
> being realistic i think no one is using those versions XD

I mean I can name a few million people using the latest version of Minecraft (I can't really I was just implying a lot of people play on the latest version of Minecraft)

**Comment by Splarkszter** [comment] 2022-08-09 06:20
well. maybe. even then, you don't need it. no big changes only nerfs. i still haven't updated. and won't untill content is delivered.

**Closed** 2022-08-15 15:55 UTC
Labels: a:enhancement, a:new-feature
