### ISSUE TITLE
[BUG] I can't connect to the server

### ISSUE THREAD

**Issue by Vencodor** [MCCTeam/Minecraft-Console-Client#2150] opened 2022-09-03 15:36 UTC
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.12.2

### Console Client Version

1.19

### Expected Behavior

I expected that the server connection would be fine.

### Actual Behavior

When trying to connect after entering the server IP "
[ERROR] InvalidOperationException: Queue empty.
[ERROR] An error occured when attempting to join this server.
" an error occurs

### Steps to Reproduce the bug

Enter server IP after login

### Anythings that could help diagnosing the bug

```txt
Minecraft Console Client v1.19 - for MC 1.4.6 to 1.19 - Github.com/MCCTeam
[MCC] [Settings] Loading Settings from C:\Users\1324q\OneDrive\바탕 화면\(New) ConsoleClient\MinecraftClient.ini
Login :
Cached session is still valid for Vencoder.
Cached profile key is still valid for Vencoder.
Server IP :
Resolving asteronline.kr...
Found server private-scn-sev46.scn.pw:1746 for domain asteronline.kr
Retrieving Server Info...
Server version : Paper 1.12.2 (protocol v340)
[MCC] Version is supported. Logging in...
[MCC] Checking Session...
[ERROR] InvalidOperationException: Queue empty.
[ERROR] An error occured when attempting to join this server.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.
```

### Device

Laptop

### Operating System

Windows

### Server Address (If applicable)

asteronline.kr

**Comment by ORelio** [comment] 2022-09-03 15:43
Looks like a duplicate of #2110

**Comment by BruceChenQAQ** [comment] 2022-09-04 12:45
Should be fixed in https://github.com/MCCTeam/Minecraft-Console-Client/pull/2124/commits/015d28ec946caba74c3559f6cd9c0912cebcfc45

**Closed** 2022-09-05 11:57 UTC
Labels: a:bug
