### ISSUE TITLE
Forge version needs to be bumpe (i think)

### ISSUE THREAD

**Issue by LOSEARDES77** [MCCTeam/Minecraft-Console-Client#2557] opened 2023-08-02 21:51 UTC
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.2

### Console Client Version

20230802-227 (Latest)

### Expected Behavior

To log into the server flawlessly

### Actual Behavior

it returns me the error attached below that says that forge version is lower than required 

### Steps to Reproduce the bug

1. log in with a premium acount
2. joi myprivate server (do you need the ip?)
3. 

### Attach screenshot here (If applicable)

Cached profile key is still valid for LOSEARDES77.
Force-enabling Forge support.

< HTTP/1.1 204 No Content
< Date: Wed, 02 Aug 2023 21:45:28 GMT
< Content-Type: application/json
< Connection: close
< x-minecraft-request-id: xxxxx
< Cache-Control: no-store
[MCC] Version is supported.
Logging in...
< x-azure-ref: xxxxxx
< X-Cache: TCP_MISS
[MCC] Login failed :
[MCC] This modded server is not impl compatible with your modded client. Please verify your Forge version closely matches the server. Got net version 2 this server is net version 3
< 
< 
[ERROR] Failed to login to this server.
  
Initialization failed.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.
   at MinecraftClient.McClient..ctor(SessionToken session, PlayerKeyPair playerKeyPair, String server_ip, UInt16 port, Int32 protocolversion, ForgeInfo forgeInfo)
   at MinecraftClient.Program.InitializeClient()

### Anythings that could help diagnosing the bug

```txt
everything works flawlessly except when i try to get into the server. this is my private serer where i play with some friends and it has minecraft forge 1.19.2 running a modpack. the console instance seams to spoof forge correctly but the forge version spoof i think it needs to be bunped.
```

### Device

VPS

### Operating System

Linux

**Comment by milutinke** [comment] 2023-08-03 07:12
Forge is supported up to 1.17/.1 in the MCC.
After which there were major changes in the protocol, and there is no documentation on it.
This is not a bug.

**Comment by LOSEARDES77** [comment] 2023-08-03 10:27
ok so what should i do to get in the server just wait for you to update it?
btw i'm not trying to make you feel bad i really apreciate your work and respect it and i would wait until necessary.
Thanks for your answer.

**Comment by milutinke** [comment] 2023-08-03 12:41
> ok so what should i do to get in the server just wait for you to update it?
> btw i'm not trying to make you feel bad i really apreciate your work and respect it and i would wait until necessary.
> Thanks for your answer.

It is not going to be implemented any time soon, unless someone is willing to go ans dig into the Forge source code, document it and implement it in the mcc.

**Comment by milutinke** [comment] 2023-11-19 11:14
Duplicate of #2309

**Closed by milutinke** 2023-11-19 11:14 UTC
Labels: a:enhancement, a:new-feature, in:forge
