### ISSUE TITLE
[BUG] /useblock cannot open containers on the arm64 architecture.

### ISSUE THREAD

**Issue by xunilalala** [MCCTeam/Minecraft-Console-Client#2508] opened 2023-05-23 13:17 UTC
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.4

### Console Client Version

Latest

### Expected Behavior

This robot can open containers and use "inventory" to view them.

### Actual Behavior

MCC indicates that I successfully used the block, but it doesn't inform me that a container has been opened.

### Steps to Reproduce the bug

1. Run MCC on an ARM processor.
2. Place any container.
3. Use "useblock" to open it.

### Attach screenshot here (If applicable)

![KX6$8 8%1T)_6A7AH@U7RH](https://github.com/MCCTeam/Minecraft-Console-Client/assets/64685627/0d580b17-df00-4157-8eed-6142d99ac849)

### Anythings that could help diagnosing the bug

```txt
In the same situation, MCC can open containers and use "/inventory" to view them on Win11, but when I run it on an ARM processor, it only tells me that I successfully used the block.
```

### Device

Other

### Operating System

Linux

**Comment by milutinke** [comment] 2023-05-23 14:46
Not related to ARM architecture, this is a bug in the MCC or the protocol itself.
Duplicate of #2443

**Closed by milutinke** 2023-05-23 14:46 UTC
Labels: a:bug
